ui: mocha-bdd
server: ./test/support/server.js
tunnel:
  type: ngrok
  authtoken: 6Aw8vTgcG5EvXdQywVvbh_54fseiTyrsQcztGc8uwB3
  proto: tcp
browsers:
  - name: chrome
    version: 29..latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: 11
    platform: Windows 2012
  - name: edge
    version: latest
    platform: Windows 10
  - name: ie
    version: [6..9, latest]
  - name: iphone
    version: 6.0..latest
  - name: android
    version: oldest..latest
    version: 5.1
